version: '3.3'

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run dev
    ports:
      - '2000:2000'
    depends_on:
      - mysql
    environment:
      DATABASE_URL: mysql://root:password@mysql:1002/mitraindb
      PORT: 2000
      JWT_SECRET: diuwahiuwahdaiu23133212uihdwa

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    command: --port=1002
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mitraindb
    volumes:
      - mitrain-db:/var/lib/mysql
    ports:
      - '1002:1002'

volumes:
  mitrain-db: