name: Node.js CI

on:
  push:
    branches: ['development']
  pull_request:
    branches: ['development']

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'

      - name: Copy .env file
        run: cp .env.example .env

      - name: Install Dependencies
        run: npm ci
      
      - name: Build
        run: npm run build
